name: publish
on: [push]
jobs:
  publish-docker:
    name: Does this need a name
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_CONTAINER_PAT }}
      - name: Build the Docker Image
        run: |
          docker build . --tag ghcr.io/$GITHUB_REPOSITORY:latest
          docker run ghcr.io/$GITHUB_REPOSITORY:latest
          docker push ghcr.io/$GITHUB_REPOSITORY:latest
          echo ${REPO_NAME}
          echo ${username}
